//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasaMenüV2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class masalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public masalar()
        {
            this.hesaps = new HashSet<hesap>();
            this.siparis = new HashSet<sipari>();
        }
    
        public int id { get; set; }
        public string adi { get; set; }
        public Nullable<int> gId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hesap> hesaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sipari> siparis { get; set; }
        public virtual grup grup { get; set; }
    }
}
