//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasaMenüV2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel
    {
        public int pId { get; set; }
        public string pName { get; set; }
        public string pPass { get; set; }
        public bool yetki { get; set; }
    }
}
